version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Login to Azure Container Registry
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Build Docker image
          command: |
            docker build -t myfirstcicdregistry.azurecr.io/my-flask-app:latest .
      - run:
          name: Log in to ACR
          command: |
            echo $AZURE_CLIENT_SECRET | docker login myfirstcicdregistry.azurecr.io --username $AZURE_CLIENT_ID --password-stdin
      - run:
          name: Push Docker image
          command: |
            docker push myfirstcicdregistry.azurecr.io/my-flask-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
