version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/python:3.9  # Use Python Docker image
    working_directory: ~/repo

jobs:
  build_and_deploy:
    executor: ubuntu-executor
    steps:
      - checkout  # Check out your code from the GitHub repository
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io  # Install Docker on the CircleCI executor
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use  # Set up Buildx for Docker multi-platform builds
      - run:
          name: Log in to Azure Container Registry
          command: |
            echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $ACR_NAME.azurecr.io/my-flask-app:latest .
            docker push $ACR_NAME.azurecr.io/my-flask-app:latest

workflows:
  version: 2
  deploy:
    jobs:
      - build_and_deploy  # Run the build and deploy job
