name: Flask App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure Container Registry
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t myfirstcicdregistry.azurecr.io/my-flask-app:latest .

    - name: Log in to ACR
      run: |
        echo ${{ secrets.AZURE_CREDENTIALS }} | docker login myfirstcicdregistry.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

    - name: Push Docker image to ACR
      run: |
        docker push myfirstcicdregistry.azurecr.io/my-flask-app:latest
