name: Flask App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Azure Container Registry
      run: |
        az acr login --name myfirstcicddockerregistry

    - name: Pull Docker Image from ACR
      run: |
        docker pull myfirstcicddockerregistry.azurecr.io/my-flask-app:latest

    - name: Run Docker container (or deploy it elsewhere)
      run: |
        docker run -d -p 5000:5000 myfirstcicddockerregistry.azurecr.io/my-flask-app:latest
