name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Trigger on changes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu-based container to build the image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use Python 3.x for building

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: myfirstdockerazregistry.azurecr.io  # Your ACR name from GitHub secrets
        username: myfirstdockerazregistry  # ACR username from GitHub secrets
        password: myfirstdockerazregistry  # ACR password from GitHub secrets

    - name: Build and Push Docker image
      run: |
        docker build -t myfirstdockerazregistry.azurecr.io/my-flask-app:latest .
        docker push myfirstdockerazregistry.azurecr.io/my-flask-app:latest